#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

pairs = {
    "about/index.html": (
        '<a href="../consultations/#contact">Консультації</a>',
        '<a href="../consultations/">Консультації</a>',
    ),
    "ru/about/index.html": (
        '<a href="../consultations/#contact">Консультации</a>',
        '<a href="../consultations/">Консультации</a>',
    ),
}

for relative, (old, new) in pairs.items():
    path = ROOT / relative
    text = path.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"{relative}: expected footer route generated by migration is missing")
    path.write_text(text.replace(old, new), encoding="utf-8")
    print(f"Restored global footer route in {relative}")
